---
- name: Install vsftpd and libs for SELinux
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Configure vsftpd and OS
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure vsftpd has selected state and enabled on boot.
  service:
    name: vsftpd
    state: started
    enabled: true