---
- name: Ensure httpd is installed on RedHat
  package:
    name: vsftpd
    state: latest

- name: Create upload dir
  file:
    path: "{{ upload_path }}"
    state: directory
    owner: ftp
    group: ftp

- name: Change Home dir
  user:
    name: ftp
    state: present
    home: "{{ ftp_path }}"

- name: install libs for selinux modul
  yum:
    name: 
      - python3-libselinux 
      - python3-libsemanage 
      - python3-policycoreutils
    state: latest

- name: Allow ftp to modify files in "{{ upload_path }}"
  sefcontext:
    target: "{{ upload_path }}"
    setype: public_content_rw_t
    reload: yes
    state: present
  notify:
    - Apply new SELinux file context to filesystem

- name: Set ftpd_anon_write
  seboolean:
    name: allow_ftpd_anon_write
    state: yes
    persistent: yes

- firewalld:
    service: ftp
    permanent: yes
    state: enabled
  notify: 
    - Reload firewalld service

- name: Create vsftpd.conf from template
  template:
    src: vsftpd.j2
    dest: /etc/vsftpd/vsftpd.conf
  notify: restart vsftpd

- name: Ensure vsftpd has selected state and enabled on boot.
  service:
    name: vsftpd
    state: started
    enabled: true